stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - _site/
  script:
    - rvm use 2.6
    - gem install jekyll bundler
    - bundle install
    - make build

deploy_review:
  stage: deploy
  script:
    - make deploy-review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.p1.ditemiku.local
    on_stop: stop_review
  except:
    refs:
      - master
      - deploy/prod

stop_review:
  stage: deploy
  script:
    - make stop-review
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  except:
    refs:
      - master
      - deploy/prod

deploy:
  stage: deploy
  only:
    refs:
      - deploy/prod
  dependencies:
    - build
  script:
    - make deploy
  environment:
    name: prod
    url: http://p1.ditemiku.local
