version: 2
jobs:
  build:
    docker:
      - image: jekyll/jekyll:3.8

    environmnet:
      JEKYLL_UID: 0
      JEKYLL_GID: 0
    working_directory: /src
    steps:
      - checkout

      - restore_cache:
          keys: [bundle]

      - run:
          command: cd /src && bundle install

      - save_cache:
          key: bundle
          paths:
            - /usr/local/bundle

      - run:
          command: |
            set -eux;
            mkdir /src/_site;
            chmod ugo+rwX /src/_site;
            make build

      - persist_to_workspace:
          root: /src
          paths:
            - _site

  deploy:
    docker:
      - image: eeacms/rsync:1.2

    working_directory: /src/_site

    steps:
      - attach_workspace:
          at: /src/_site

      - run:
          command: ls -lA && echo "Deploy step would be here"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build: {}
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
